# Generated by Django 5.2.7 on 2025-10-29 13:16

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the bus route', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='A short description of the route')),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(help_text='The geographical path of the route', srid=4326)),
                ('operator', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('destination', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('is_driver', models.BooleanField(default=False)),
                ('is_commuter', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('capacity', models.IntegerField()),
                ('speed_mps', models.FloatField(default=0.0)),
                ('current_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('last_reported_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.customuserprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(help_text='The order of the stop along the route')),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='The geographical location of the stop', srid=4326)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='api.route')),
            ],
            options={
                'ordering': ['route', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('estimated_arrival_time', models.DateTimeField(blank=True, null=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='api.bus')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='api.route')),
            ],
        ),
        migrations.CreateModel(
            name='VehiclePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('heading_deg', models.FloatField(blank=True, null=True)),
                ('speed_mps', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='api.bus')),
            ],
            options={
                'indexes': [models.Index(fields=['bus', 'recorded_at'], name='api_vehicle_bus_id_a168ac_idx')],
            },
        ),
    ]
