# Generated by Django 5.2.6 on 2025-10-08 19:12

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('capacity', models.IntegerField()),
                ('speed_mps', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('routes', models.ManyToManyField(blank=True, related_name='locations', to='api.route')),
            ],
            options={
                'unique_together': {('point',)},
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('estimated_arrival_time', models.DateTimeField(blank=True, null=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='api.bus')),
                ('current_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.location')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='api.route')),
            ],
        ),
        migrations.CreateModel(
            name='VehiclePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('heading_deg', models.FloatField(blank=True, null=True)),
                ('speed_mps', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='api.bus')),
            ],
            options={
                'indexes': [models.Index(fields=['bus', 'recorded_at'], name='api_vehicle_bus_id_a168ac_idx')],
            },
        ),
    ]
