# Generated by Django 5.2.6 on 2025-11-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_trip_current_stop_alter_bus_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('started', 'Started'), ('finished', 'Finished')], default='pending', max_length=16),
        ),
    ]
