# Generated by Django 5.2.6 on 2025-09-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_location_name_remove_route_previous_route_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
