# Generated by Django 5.2.6 on 2025-12-06 21:59

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_trip_finished_at_trip_started_at_trip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact phone number', max_length=128, region=None),
        ),
    ]
