# Generated by Django 5.2.6 on 2025-09-30 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_location_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['route', 'order']},
        ),
        migrations.RemoveField(
            model_name='bus',
            name='Bus_ID',
        ),
        migrations.AddField(
            model_name='bus',
            name='current_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='current_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='location',
            name='cum_km',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='location',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='api.route'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('route', 'order')},
        ),
    ]
