# Generated by Django 5.2.7 on 2025-10-16 22:18

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuserprofile_alter_bus_driver_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserprofile',
            name='current_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='customuserprofile',
            name='destination',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
