# Generated by Django 5.2.6 on 2025-12-08 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customuserprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='assigned_route',
            field=models.ForeignKey(blank=True, help_text='Route currently assigned to this bus (not necessarily active trip)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buses_assigned', to='api.route'),
        ),
    ]
