# Generated by Django 5.2.7 on 2025-10-17 08:17

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_customuserprofile_current_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='geometry',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
