# Generated by Django 5.2.7 on 2025-10-22 16:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_route_geometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='current_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='bus',
            name='last_reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
