# Generated by Django 5.2.6 on 2025-12-13 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_bus_assigned_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserprofile',
            name='destination_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riders_destination', to='api.route'),
        ),
        migrations.AddField(
            model_name='customuserprofile',
            name='destination_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riders_destination', to='api.stop'),
        ),
        migrations.AddField(
            model_name='customuserprofile',
            name='origin_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riders_origin', to='api.stop'),
        ),
    ]
