# Generated by Django 5.2.6 on 2025-09-30 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_bus_id_alter_location_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='id',
        ),
        migrations.AddField(
            model_name='bus',
            name='Bus_ID',
            field=models.AutoField(db_column='Bus_ID', primary_key=True, serialize=False),
        ),
    ]
