# Generated by Django 5.2.6 on 2025-12-13 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_customuserprofile_destination_route_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
