# Generated by Django 5.2.6 on 2025-12-14 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_fill_stop_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserprofile',
            name='selected_end_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers_selected_end', to='api.stop'),
        ),
        migrations.AddField(
            model_name='customuserprofile',
            name='selected_start_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers_selected_start', to='api.stop'),
        ),
    ]
